TypeError: port.on is not a function
TypeError: port.on is not a function suggests that the createSerial function does not return an object with an on method. This might be due to the way the serial port is being set up in your environment....